### ISSUE TITLE
Что это?

### ISSUE THREAD

**Issue by Azq2** [DemonSinusa/SiemanC#1]
WTF вообще?)

**Comment by Azq2** [comment]
Ещё кто-то пишет под сименсы>?!??

**Comment by DemonSinusa** [comment]
Тип того) лучший самоучитель по программированию!

2016-10-08 22:17 GMT+03:00 Кирилл Жумарин <notifications@github.com>:

**Comment by Azq2** [comment]
По аццкому костылированию скорее :D

**Comment by DemonSinusa** [comment]
Ну кому как)

2016-11-18 3:23 GMT+03:00 Кирилл Жумарин notifications@github.com:

**Comment by Azq2** [comment]
Tonich?)

**Comment by DemonSinusa** [comment]
Yes! :)
